sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script: pwd && ./deploy.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  repo: minbaby.github.io
  target_branch: master
  verbose: true