version: '3'
services: 
  hugo: &base
    image: klakegg/hugo:0.60.0-busybox
    command: -D -F
    volumes:
      - .:/src
      - ./output:/src/target
  run-web:
    <<: *base
    command: server -D -F
    ports:
      - 1313:1313