version: '3'
services: 
  hugo: &base
    image: klakegg/hugo:busybox
    command: -D -F
    user: "1000:1000"
    volumes:
      - .:/src
      - ./output:/src/target
  run-web:
    <<: *base
    command: server -D -F
    ports:
      - 1313:1313