
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: cibuilds/hugo:latest

    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: public

    steps:
      # - add_ssh_keys:
      #     fingerprints:
      #       - "c8:4a:67:87:93:38:c4:c3:1c:27:aa:8b:0f:d4:d8:23"
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: ./.circleci/deploy.sh